format = """
$os$username(bg:#292e42 fg:#c0caf5)\
[](bg:#bb9af7 fg:#292e42)\
$directory\
[](bg:#7dcfff fg:#bb9af7)\
$git_branch$git_status\
[](bg:#7aa2f7 fg:#7dcfff)\
$deno\
$golang\
$lua\
$nodejs\
[ ](fg:#7aa2f7)\
"""

right_format = ""

# GIT
# ===

[git_branch]
format = "[ $symbol$branch(:$remote_branch) ]($style)"
symbol = "󰘬 "
style = "fg:#1a1b26 bg:#7dcfff"

[git_status]
style = "fg:#1a1b26 bg:#7dcfff"
format = '[($all_status$ahead_behind )]($style)'

# LANGUAGES
# =========

[lua]
symbol = '󰢱 '
format = '[ $symbol($version )]($style)'
style = "fg:#1a1b26 bg:#7aa2f7"

[golang]
symbol = '󰟓 '
format = '[ $symbol($version )]($style)'
style = "fg:#1a1b26 bg:#7aa2f7"

[deno]
symbol = 'Deno '
format = '[ $symbol($version )]($style)'
style = "fg:#1a1b26 bg:#7aa2f7"

[nodejs]
symbol = '󰎙 '
format = "[ $symbol($version )]($style)"
style = "fg:#1a1b26 bg:#7aa2f7"

# MISC
# ====

[hostname]
ssh_only = false
style = "fg:#c0caf5 bg:#292e42"
format = "[$ssh_symbol$hostname ]($style)"
ssh_symbol = " "

[os]
style = "fg:#c0caf5 bg:#292e42"
disabled = false

[os.symbols]
Arch = '  '
Fedora = '  '
Ubuntu = '  '
Macos = '  '
Pop = '  '
CachyOS = '  '

[shell]
disabled = false

[username]
show_always = true
format = '[$user ]($style)'
style_user = "fg:#c0caf5 bg:#292e42"

[directory]
style = "fg:#1a1b26 bg:#bb9af7"
read_only = " "
format = "[ 󰉋 $path ]($style)[$read_only]($read_only_style)"
read_only_style = "fg:#1a1b26 bold bg:#bb9af7"

[sudo]
disabled = false
symbol = " "
style = "fg:#c0caf5 bg:#292e42"
format = "[ $symbol]($style)"

[cmd_duration]
format = "[ 󰔚 $duration ]($style)"
style = "fg:#c0caf5 bg:#292e42"

[character]
success_symbol = "[ 󱞩](bold green)"
error_symbol = "[ 󱞩](bold red)"
vimcmd_symbol = "[  󱞩](bold green)"

[battery]
disabled = true
