pragma Singleton
import QtQuick
import Quickshell
import qs

// Material 3 design tokens derived from the active theme's Colors.qml.
// Colors.qml is regenerated by theme-switcher/hooks/quickshell.sh on every
// theme switch, so this file must NOT be regenerated — it recomputes from
// Colors automatically (the hook restarts quickshell, so tokens re-evaluate).
// No per-theme files are touched: containers/state-layers are blended from
// the existing palette, keeping the exact same color schemes.
Singleton {
  // ---- public helpers (used by consumers) ----
  function mix(c1, c2, t) {
    return Qt.rgba(c1.r * (1 - t) + c2.r * t,
                   c1.g * (1 - t) + c2.g * t,
                   c1.b * (1 - t) + c2.b * t,
                   1)
  }

  function alpha(c, a) {
    return Qt.rgba(c.r, c.g, c.b, a)
  }

  function luminance(c) {
    return 0.2126 * c.r + 0.7152 * c.g + 0.0722 * c.b
  }

  // Pick dark or light text that reads on a given fill.
  function onColor(c) {
    return Tokens.luminance(c) > 0.45 ? Colors.base : Colors.text
  }

  // ---- surfaces (tonal elevation) ----
  readonly property color surfaceContainerLowest: Colors.base
  readonly property color surfaceContainerLow: Colors.surface
  readonly property color surfaceContainer: Colors.surface_alt
  readonly property color surfaceContainerHigh: Colors.surface_high
  readonly property color surfaceContainerHighest: Colors.surface_highest

  // ---- semantics ----
  readonly property color on_surface: Colors.text
  readonly property color on_surface_variant: Colors.text_alt
  readonly property color outline: Colors.muted
  readonly property color outlineVariant: Colors.outline_variant
  readonly property color divider: Colors.divider

  // ---- primary ----
  // NOTE: property names must NEVER match `on` + UppERCASE (e.g. onPrimary) —
  // QML parses those as signal handlers, so the property silently never exists
  // and every consumer falls back to black text. Hence snake_case on_*.
  readonly property color primary: Colors.primary
  readonly property color on_primary: Colors.text
  readonly property color primaryContainer: Colors.primary_container
  readonly property color on_primary_container: Colors.on_primary_container

  // ---- secondary (primary_alt) ----
  readonly property color secondary: Colors.primary_alt
  readonly property color on_secondary: Colors.text
  readonly property color secondaryContainer: Tokens.mix(Colors.surface, Colors.primary_alt, 0.25)
  readonly property color on_secondary_container: Colors.text

  // ---- tertiary (accent) ----
  readonly property color tertiary: Colors.accent
  readonly property color on_tertiary: Colors.text
  readonly property color tertiaryContainer: Tokens.mix(Colors.surface, Colors.accent, 0.25)
  readonly property color on_tertiary_container: Colors.text

  // ---- success / warning / error ----
  // All themes are dark backgrounds with light text; keep every "on-container"
  // text light (Colors.text) so it stays readable on the darker tinted fills.
  readonly property color success: Colors.success
  readonly property color on_success: Colors.text
  readonly property color successContainer: Tokens.mix(Colors.surface, Colors.success, 0.25)
  readonly property color on_success_container: Colors.text
  readonly property color warning: Colors.warning
  readonly property color on_warning: Colors.text
  readonly property color warningContainer: Tokens.mix(Colors.surface, Colors.warning, 0.25)
  readonly property color on_warning_container: Colors.text
  readonly property color error: Colors.error
  readonly property color on_error: Colors.text
  readonly property color errorContainer: Tokens.mix(Colors.surface, Colors.error, 0.25)
  readonly property color on_error_container: Colors.text

  // ---- state layers ----
  readonly property color stateHover: Qt.rgba(Colors.text.r, Colors.text.g, Colors.text.b, 0.08)
  readonly property color statePressed: Qt.rgba(Colors.text.r, Colors.text.g, Colors.text.b, 0.12)
  readonly property color stateFocus: Qt.rgba(Colors.primary.r, Colors.primary.g, Colors.primary.b, 0.1)
  readonly property color stateDisabled: Qt.rgba(Colors.text.r, Colors.text.g, Colors.text.b, 0.38)

  readonly property color scrim: Qt.rgba(0, 0, 0, 0.4)
}