# One Dark
base=#282C34
surface=#2C323C
surface_alt=#3E4452
text=#ABB2BF
text_alt=#98A0AD
muted=#5C6370
border=#4B5263
primary=#61AFEF
primary_alt=#56B6C2
accent=#56B6C2
success=#98C379
warning=#E5C07B
error=#E06C75
urgent=#E06C75
