format = """
$os$username(bg:#3E4452 fg:#ABB2BF)\
[](bg:#61AFEF fg:#3E4452)\
$directory\
[](bg:#56B6C2 fg:#61AFEF)\
$git_branch$git_status\
[](bg:#56B6C2 fg:#56B6C2)\
$deno\
$golang\
$lua\
$nodejs\
[ ](fg:#56B6C2)\
"""

# GIT
# ===

[git_branch]
format = "[ $symbol$branch(:$remote_branch) ]($style)"
symbol = "󰘬 "
style = "fg:#282C34 bg:#56B6C2"

[git_status]
style = "fg:#282C34 bg:#56B6C2"
format = '[($all_status$ahead_behind )]($style)'

# LANGUAGES
# =========

[lua]
symbol = '󰢱 '
format = '[ $symbol($version )]($style)'
style = "fg:#282C34 bg:#56B6C2"

[golang]
symbol = '󰟓 '
format = '[ $symbol($version )]($style)'
style = "fg:#282C34 bg:#56B6C2"

[deno]
symbol = 'Deno '
format = '[ $symbol($version )]($style)'
style = "fg:#282C34 bg:#56B6C2"

[nodejs]
symbol = '󰎙 '
format = "[ $symbol($version )]($style)"
style = "fg:#282C34 bg:#56B6C2"

# MISC
# ====

[hostname]
ssh_only = false
style = "fg:#ABB2BF bg:#3E4452"
format = "[$ssh_symbol$hostname ]($style)"
ssh_symbol = " "

[os]
style = "fg:#ABB2BF bg:#3E4452"
disabled = false

[os.symbols]
Arch = '  '
Fedora = '  '
Ubuntu = '  '
Macos = '  '
Pop = '  '
CachyOS = '  '

[shell]
disabled = false

[username]
show_always = true
format = '[$user ]($style)'
style_user = "fg:#ABB2BF bg:#3E4452"

[directory]
style = "fg:#282C34 bg:#61AFEF"
read_only = " "
format = "[ 󰉋 $path ]($style)[$read_only]($read_only_style)"
read_only_style = "fg:#282C34 bold bg:#61AFEF"

[sudo]
disabled = false
symbol = " "
style = "fg:#ABB2BF bg:#3E4452"
format = "[ $symbol]($style)"

[cmd_duration]
format = "[ 󰔚 $duration ]($style)"
style = "fg:#ABB2BF bg:#3E4452"

[character]
success_symbol = "[ 󱞩](bold green)"
error_symbol = "[ 󱞩](bold red)"
vimcmd_symbol = "[  󱞩](bold green)"
