set -g @tmux_base "#282C34"
set -g @tmux_surface "#2C323C"
set -g @tmux_text "#ABB2BF"
set -g @tmux_muted "#5C6370"
set -g @tmux_border "#4B5263"
set -g @tmux_primary "#61AFEF"
set -g @tmux_accent "#56B6C2"
set -g @tmux_success "#98C379"
set -g @tmux_warning "#E5C07B"
set -g @tmux_error "#E06C75"
set -g @tmux_danger "#E06C75"
