set -g prefix C-s

set -g mouse on

set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on

set -g status-position top
set -g clock-mode-style 12

# Enable true color support
set -g default-terminal "screen-256color"
set -ga terminal-overrides ",xterm-256color:Tc"
