# Catppuccin Mocha
base=#11111b
surface=#181825
surface_alt=#313244
text=#cdd6f4
text_alt=#bac2de
muted=#6c7086
border=#45475a
primary=#b4befe
primary_alt=#89b4fa
accent=#94e2d5
success=#a6e3a1
warning=#f9e2af
error=#f38ba8
urgent=#f38ba8
