format = """
$os$username(bg:#434C5E fg:#D8DEE9)\
[](bg:#81A1C1 fg:#434C5E)\
$directory\
[](bg:#8FBCBB fg:#81A1C1)\
$git_branch$git_status\
[](bg:#88C0D0  fg:#8FBCBB)\
$deno\
$golang\
$lua\
$nodejs\
[ ](fg:#88C0D0)\
"""

right_format = ""

# GIT
# ===

[git_branch]
format = "[ $symbol$branch(:$remote_branch) ]($style)"
symbol = "󰘬 "
style = "fg:#2E3440 bg:#8FBCBB"

[git_status]
style = "fg:#2E3440 bg:#8FBCBB"
format = '[($all_status$ahead_behind )]($style)'

# LANGUAGES
# =========

[lua]
symbol = '󰢱 '
format = '[ $symbol($version )]($style)'
style = "fg:#2E3440 bg:#88C0D0"

[golang]
symbol = '󰟓 '
format = '[ $symbol($version )]($style)'
style = "fg:#2E3440 bg:#88C0D0"

[deno]
symbol = 'Deno '
format = '[ $symbol($version )]($style)'
style = "fg:#2E3440 bg:#88C0D0"

[nodejs]
symbol = '󰎙 '
format = "[ $symbol($version )]($style)"
style = "fg:#2E3440 bg:#88C0D0"

# MISC
# ====

[hostname]
ssh_only = false
style = "fg:#D8DEE9 bg:#434C5E"
format = "[$ssh_symbol$hostname ]($style)"
ssh_symbol = " "

[os]
style = "fg:#D8DEE9 bg:#434C5E"
disabled = false

[os.symbols]
Arch = '  '
Fedora = '  '
Ubuntu = '  '
Macos = '  '
Pop = '  '
CachyOS = '  '

[shell]
disabled = false

[username]
show_always = true
format = '[$user ]($style)'
style_user = "fg:#D8DEE9 bg:#434C5E"

[directory]
style = "fg:#2E3440 bg:#81A1C1"
read_only = " "
format = "[ 󰉋 $path ]($style)[$read_only]($read_only_style)"
read_only_style = "fg:#2E3440 bold bg:#81A1C1"

[sudo]
disabled = false
symbol = " "
style = "fg:#D8DEE9 bg:#434C5E"
format = "[ $symbol]($style)"

[cmd_duration]
format = "[ 󰔚 $duration ]($style)"
style = "fg:#D8DEE9 bg:#434C5E"

[character]
success_symbol = "[ 󱞩](bold green)"
error_symbol = "[ 󱞩](bold red)"
vimcmd_symbol = "[  󱞩](bold green)"

[battery]
disabled = true
