set -g @tmux_base "#2E3440"
set -g @tmux_surface "#3B4252"
set -g @tmux_text "#D8DEE9"
set -g @tmux_muted "#4C566A"
set -g @tmux_border "#434C5E"
set -g @tmux_primary "#88C0D0"
set -g @tmux_accent "#8FBCBB"
set -g @tmux_success "#A3BE8C"
set -g @tmux_warning "#EBCB8B"
set -g @tmux_error "#BF616A"
set -g @tmux_danger "#BF616A"
