format = """
$os$username(bg:#2E383C fg:#D3C6AA)\
[](bg:#7FBBB3 fg:#2E383C)\
$directory\
[](bg:#83C092 fg:#7FBBB3)\
$git_branch$git_status\
[](bg:#D699B6 fg:#83C092)\
$deno\
$golang\
$lua\
$nodejs\
[ ](fg:#D699B6)\
"""

# GIT
# ===

[git_branch]
format = "[ $symbol$branch(:$remote_branch) ]($style)"
symbol = "󰘬 "
style = "fg:#1E2326 bg:#83C092"

[git_status]
style = "fg:#1E2326 bg:#83C092"
format = '[($all_status$ahead_behind )]($style)'

# LANGUAGES
# =========

[lua]
symbol = '󰢱 '
format = '[ $symbol($version )]($style)'
style = "fg:#1E2326 bg:#D699B6"

[golang]
symbol = '󰟓 '
format = '[ $symbol($version )]($style)'
style = "fg:#1E2326 bg:#D699B6"

[deno]
symbol = 'Deno '
format = '[ $symbol($version )]($style)'
style = "fg:#1E2326 bg:#D699B6"

[nodejs]
symbol = '󰎙 '
format = "[ $symbol($version )]($style)"
style = "fg:#1E2326 bg:#D699B6"

# MISC
# ====

[hostname]
ssh_only = false
style = "fg:#D3C6AA bg:#2E383C"
format = "[$ssh_symbol$hostname ]($style)"
ssh_symbol = " "

[os]
style = "fg:#D3C6AA bg:#2E383C"
disabled = false

[os.symbols]
Arch = '  '
Fedora = '  '
Ubuntu = '  '
Macos = '  '
Pop = '  '
CachyOS = '  '

[shell]
disabled = false

[username]
show_always = true
format = '[$user ]($style)'
style_user = "fg:#D3C6AA bg:#2E383C"

[directory]
style = "fg:#1E2326 bg:#7FBBB3"
read_only = " "
format = "[ 󰉋 $path ]($style)[$read_only]($read_only_style)"
read_only_style = "fg:#1E2326 bold bg:#7FBBB3"

[sudo]
disabled = false
symbol = " "
style = "fg:#D3C6AA bg:#2E383C"
format = "[ $symbol]($style)"

[cmd_duration]
format = "[ 󰔚 $duration ]($style)"
style = "fg:#D3C6AA bg:#2E383C"

[character]
success_symbol = "[ 󱞩](bold green)"
error_symbol = "[ 󱞩](bold red)"
vimcmd_symbol = "[  󱞩](bold green)"
