set -g @tmux_base "#1E2326"
set -g @tmux_surface "#272E33"
set -g @tmux_text "#D3C6AA"
set -g @tmux_muted "#7A8478"
set -g @tmux_border "#414B50"
set -g @tmux_primary "#7FBBB3"
set -g @tmux_accent "#83C092"
set -g @tmux_success "#A7C080"
set -g @tmux_warning "#DBBC7F"
set -g @tmux_error "#E67E80"
set -g @tmux_danger "#E67E80"
