-- Autostart
hl.on("hyprland.start", function()
    hl.exec_cmd("awww-daemon")
    hl.exec_cmd("~/.config/kmdot/hyprland/scripts/apply_wallpaper.sh")
    hl.exec_cmd("quickshell &")
    hl.exec_cmd("~/.config/kmdot/quickshell/scripts/clipboard-daemon.sh &")
    hl.exec_cmd("hypridle &")
    hl.exec_cmd("swaync")
    hl.exec_cmd("nm-applet")
    hl.exec_cmd("~/.config/kmdot/hyprland/scripts/manage_workspaces.sh")
    hl.exec_cmd("gnome-keyring-daemon --start --components=secrets")
end)
