# Autostart
exec-once = awww-daemon
exec-once = ~/.config/hypr/scripts/apply_wallpaper.sh
exec-once = waybar &
exec-once = hypridle &
exec-once = swaync
exec-once = nm-applet

exec-once = ~/.config/hypr/scripts/manage_workspaces.sh
exec-once = ~/.config/hypr/scripts/cycle_wallpapers.sh
