pam {
  service = login
}

general {
  hide_cursor = true
}

background {
  monitor =
  color = rgba(20, 20, 20, 1.0)
}

input-field {
  monitor =
  size = 320, 50
  outline_thickness = 2
  dots_size = 0.25
  dots_spacing = 0.2
  dots_center = true
  fade_on_empty = false
  inner_color = rgba(0, 0, 0, 0.3)
  outer_color = rgba(255, 255, 255, 0.3)
  font_color = rgba(255, 255, 255, 0.95)
  placeholder_text = Enter password
  position = 0, -20
  halign = center
  valign = center
}

label {
  monitor =
  text = Locked
  color = rgba(255, 255, 255, 0.85)
  position = 0, 70
  halign = center
  valign = center
}
