pam {
  service = login
}

general {
  hide_cursor = true
}

background {
  monitor =
  path = /usr/share/backgrounds/kmdot-ign_astronaut.png
  color = rgba(0, 0, 0, 1.0)
  blur_size = 2
  blur_passes = 1
}

label {
  monitor =
  text = cmd[update:1000] date +"%a %I:%M %p"
  color = rgba(255, 255, 255, 0.95)
  font_size = 13
  position = -20, 20
  halign = right
  valign = top
}

shape {
  monitor =
  size = 100, 100
  color = rgba(255, 255, 255, 0.2)
  border_color = rgba(255, 255, 255, 0.4)
  border_size = 1
  rounding = 50
  position = 0, 140
  halign = center
  valign = center
}

label {
  monitor =
  text = cmd[once] sh -c 'printf "%s" "${USER:-G}" | cut -c1 | tr "[:lower:]" "[:upper:]"'
  color = rgba(255, 255, 255, 1.0)
  font_size = 42
  position = 0, 140
  halign = center
  valign = center
}

label {
  monitor =
  text = $USER
  color = rgba(255, 255, 255, 1.0)
  font_size = 22
  position = 0, 50
  halign = center
  valign = center
}

input-field {
  monitor =
  size = 180, 32
  rounding = 16
  outline_thickness = 0
  dots_size = 0.25
  dots_spacing = 0.2
  dots_center = true
  fade_on_empty = false
  inner_color = rgba(255, 255, 255, 0.25)
  outer_color = rgba(255, 255, 255, 0.0)
  font_color = rgba(255, 255, 255, 1.0)
  placeholder_text = Enter Password
  position = 0, 0
  halign = center
  valign = center
}

shape {
  monitor =
  size = 44, 44
  color = rgba(255, 255, 255, 0.0)
  border_color = rgba(255, 255, 255, 0.6)
  border_size = 1.5
  rounding = 22
  position = -228, -60
  halign = right
  valign = bottom
}

label {
  monitor =
  text = P
  color = rgba(255, 255, 255, 1.0)
  font_size = 20
  position = -228, -60
  halign = right
  valign = bottom
}

label {
  monitor =
  text = Shut Down
  color = rgba(255, 255, 255, 1.0)
  font_size = 12
  position = -228, -20
  halign = right
  valign = bottom
}

shape {
  monitor =
  size = 44, 44
  color = rgba(255, 255, 255, 0.0)
  border_color = rgba(255, 255, 255, 0.6)
  border_size = 1.5
  rounding = 22
  position = -144, -60
  halign = right
  valign = bottom
}

label {
  monitor =
  text = R
  color = rgba(255, 255, 255, 1.0)
  font_size = 22
  position = -144, -60
  halign = right
  valign = bottom
}

label {
  monitor =
  text = Restart
  color = rgba(255, 255, 255, 1.0)
  font_size = 12
  position = -144, -20
  halign = right
  valign = bottom
}

shape {
  monitor =
  size = 44, 44
  color = rgba(255, 255, 255, 0.0)
  border_color = rgba(255, 255, 255, 0.6)
  border_size = 1.5
  rounding = 22
  position = -60, -60
  halign = right
  valign = bottom
}

label {
  monitor =
  text = S
  color = rgba(255, 255, 255, 1.0)
  font_size = 20
  position = -60, -60
  halign = right
  valign = bottom
}

label {
  monitor =
  text = Sleep
  color = rgba(255, 255, 255, 1.0)
  font_size = 12
  position = -60, -20
  halign = right
  valign = bottom
}
