set -g status on
set -g status-justify left
set -g status-left-length 200
set -g status-right-length 0
set -g status-right ""

set -g status-style "fg=#{@tmux_text},bg=#{@tmux_base}"
set -g message-style "fg=#{@tmux_text},bg=#{@tmux_surface}"
set -g message-command-style "fg=#{@tmux_text},bg=#{@tmux_surface}"

set -g pane-border-style "fg=#{@tmux_border}"
set -g pane-active-border-style "fg=#{@tmux_primary}"

set -g window-status-style "fg=#{@tmux_text},bg=#{@tmux_base}"
set -g window-status-current-style "fg=#{@tmux_base},bg=#{@tmux_primary},bold"

set -g status-left-style "fg=#{@tmux_text},bg=#{@tmux_base}"
set -g status-left "#{?client_prefix,#[fg=#{@tmux_danger}]#[bg=#{@tmux_base}]#[bold] kmDot,#[fg=#{@tmux_primary}]#[bg=#{@tmux_base}]#[bold] kmDot}#[fg=#{@tmux_muted}]#[bg=#{@tmux_base}] | #[fg=#{@tmux_text}]#[bg=#{@tmux_base}] "

set -g window-status-format "#[fg=#{@tmux_text},bg=#{@tmux_base}]#I. #(basename #{pane_current_path}) "
set -g window-status-current-format "#[fg=#{@tmux_base},bg=#{@tmux_primary},bold] #I. #(basename #{pane_current_path}) #[fg=#{@tmux_text},bg=#{@tmux_base}] "
